name = 'hugo-backtothe90s'
license = 'MIT'
licenselink = 'https://github.com/chardidathing/hugo-backtothe90s/blob/main/LICENSE'
description = 'A retro 90s-style blog theme for Hugo'

homepage = 'https://github.com/chardidathing/hugo-backtothe90s'
demosite = 'https://chardidath.ing'

tags = ['blog', 'diary', 'retro', '90s', 'personal']
features = ['responsive', 'simple', 'retro-style']

[author]
  name = 'chardidathing'
  homepage = 'https://chardidath.ing/'
